const fs = require('fs');
const path = require('path');

const viewsPath = path.join(__dirname, 'views');
const adminPath = path.join(viewsPath, 'admin');

const files = {
  'archive.ejs': '<div class="glass glass-panel fade-in text-center" style="margin-top:2rem; padding:4rem 2rem;"><h1>Archive</h1><p>Posts grouped by month and year will appear here.</p></div>',
  'about.ejs': '<div class="glass glass-panel fade-in" style="margin-top:2rem; padding:4rem 2rem; max-width:800px; margin:2rem auto;"><h1 class="text-center">About Us</h1><p class="text-center">Welcome to Malayalam Blog.</p></div>',
  'contact.ejs': '<div class="glass glass-panel fade-in" style="margin-top:2rem; padding:4rem 2rem; max-width:800px; margin:2rem auto;"><h1 class="text-center">Contact Us</h1><form action="/contact" method="POST" class="ajax-form"><div class="form-group"><label>Name</label><input type="text" name="name" class="form-control" required></div><div class="form-group"><label>Email</label><input type="email" name="email" class="form-control" required></div><div class="form-group"><label>Message</label><textarea name="message" class="form-control" rows="5" required></textarea></div><button type="submit" class="btn">Send Message</button></form></div>',
  'privacy.ejs': '<div class="glass glass-panel fade-in" style="margin-top:2rem; padding:4rem 2rem; max-width:800px; margin:2rem auto;"><h1>Privacy Policy</h1><p>Your privacy is important to us.</p></div>',
  'terms.ejs': '<div class="glass glass-panel fade-in" style="margin-top:2rem; padding:4rem 2rem; max-width:800px; margin:2rem auto;"><h1>Terms & Conditions</h1><p>Please read these terms carefully.</p></div>',
  'maintenance.ejs': '<!DOCTYPE html><html lang="ml"><head><title><%= title %></title><link rel="stylesheet" href="/css/style.css"></head><body style="display:flex; align-items:center; justify-content:center; height:100vh; text-align:center;"><div class="glass glass-panel"><h1>Maintenance</h1><p><%= message %></p></div></body></html>',
  '404.ejs': '<div class="glass glass-panel text-center fade-in" style="margin-top:4rem; padding:4rem 2rem;"><h1 style="font-size:4rem; margin-bottom:1rem;">404</h1><p style="font-size:1.2rem; color:var(--text-secondary); margin-bottom:2rem;">ഈ പേജ് കണ്ടെത്തിയില്ല (Page Not Found)</p><a href="/" class="btn">ഹോം പേജിലേക്ക് മടങ്ങുക</a></div>',
  '500.ejs': '<div class="glass glass-panel text-center fade-in" style="margin-top:4rem; padding:4rem 2rem;"><h1 style="font-size:4rem; margin-bottom:1rem;">500</h1><p style="font-size:1.2rem; color:var(--text-secondary); margin-bottom:2rem;">സെർവർ പിശക് (Internal Server Error)</p><a href="/" class="btn">ഹോം പേജിലേക്ക് മടങ്ങുക</a></div>',
  '403.ejs': '<div class="glass glass-panel text-center fade-in" style="margin-top:4rem; padding:4rem 2rem;"><h1 style="font-size:4rem; margin-bottom:1rem;">403</h1><p style="font-size:1.2rem; color:var(--text-secondary); margin-bottom:2rem;">നിങ്ങൾക്ക് ഈ പേജ് കാണാനുള്ള അനുമതിയില്ല (Access Denied)</p><a href="/" class="btn">ഹോം പേജിലേക്ക് മടങ്ങുക</a></div>',
  
  // Admin Views
  'admin/login.ejs': '<!DOCTYPE html><html lang="en"><head><title><%= title %></title><link rel="stylesheet" href="/css/style.css"></head><body style="display:flex; align-items:center; justify-content:center; height:100vh;"><div class="glass glass-panel" style="width:400px; padding:3rem;"><h2 class="text-center" style="margin-bottom:2rem; font-family:\'Playfair Display\', serif;">Admin Login</h2><% if(error_msg && error_msg.length > 0){ %><div class="toast glass toast-error" style="position:relative; margin-bottom:1rem; border-left:4px solid var(--error); padding:1rem;"><%= error_msg %></div><% } %><form action="/admin/login" method="POST"><div class="form-group"><label>Email</label><input type="email" name="email" class="form-control" required></div><div class="form-group"><label>Password</label><input type="password" name="password" class="form-control" required></div><button type="submit" class="btn" style="width:100%;">Login</button></form></div></body></html>',
  'admin/dashboard.ejs': '<h2 style="margin-bottom:2rem;">Dashboard</h2><div class="stats-grid"><div class="glass glass-panel stat-card"><div class="stat-value"><%= stats.posts %></div><div class="stat-label">Posts</div></div><div class="glass glass-panel stat-card"><div class="stat-value"><%= stats.views %></div><div class="stat-label">Views</div></div><div class="glass glass-panel stat-card"><div class="stat-value"><%= stats.pendingComments %></div><div class="stat-label">Pending Comments</div></div></div>',
  'admin/posts.ejs': '<div style="display:flex; justify-content:space-between; margin-bottom:2rem;"><h2>Posts</h2><a href="/admin/posts/new" class="btn">New Post</a></div><div class="glass glass-panel admin-table-container"><table class="admin-table"><thead><tr><th>Title</th><th>Status</th><th>Views</th><th>Date</th><th>Actions</th></tr></thead><tbody><% posts.forEach(post => { %><tr><td><a href="/post/<%= post.slug %>?preview=true" target="_blank" style="color:var(--text-primary);"><%= post.title %></a></td><td><span class="badge badge-<%= post.status %>"><%= post.status %></span></td><td><%= post.views %></td><td><%= new Date(post.created_at).toLocaleDateString() %></td><td><a href="/admin/posts/edit/<%= post.id %>" class="btn btn-secondary" style="padding:0.2rem 0.5rem;"><i class="fas fa-edit"></i></a> <form action="/admin/posts/delete/<%= post.id %>" method="POST" style="display:inline;" onsubmit="return confirm(\'Delete this post?\')"><button type="submit" class="btn btn-secondary" style="padding:0.2rem 0.5rem; color:var(--error);"><i class="fas fa-trash"></i></button></form></td></tr><% }) %></tbody></table></div>',
  'admin/post-editor.ejs': '<div style="display:flex; justify-content:space-between; margin-bottom:2rem;"><h2><%= title %></h2><a href="/admin/posts" class="btn btn-secondary">Back</a></div><form id="post-form" action="<%= post.id ? \'/admin/posts/edit/\'+post.id : \'/admin/posts/new\' %>" method="POST"><div class="grid-layout"><div class="glass glass-panel"><div class="form-group"><label>Title</label><input type="text" name="title" class="form-control" value="<%= post.title || \'\' %>" required></div><div class="form-group"><label>Content</label><textarea id="content" name="content" class="form-control"><%= post.content || \'\' %></textarea></div><div style="display:flex; justify-content:space-between; color:var(--text-secondary); font-size:0.85rem; margin-top:1rem;"><span>Words: <span id="word-count">0</span></span><span>Read Time: <span id="read-time">0</span> min</span></div></div><div class="glass glass-panel"><div class="form-group"><label>Status</label><select name="status" class="form-control"><option value="draft" <%= post.status === \'draft\' ? \'selected\' : \'\' %>>Draft</option><option value="published" <%= post.status === \'published\' ? \'selected\' : \'\' %>>Published</option><option value="scheduled" <%= post.status === \'scheduled\' ? \'selected\' : \'\' %>>Scheduled</option></select></div><div class="form-group"><label>Categories</label><select name="categories" class="form-control" multiple style="height:100px;"><% categories.forEach(c => { %><option value="<%= c.id %>" <%= postCategories.includes(c.id) ? \'selected\' : \'\' %>><%= c.name %></option><% }) %></select></div><div class="form-group"><label>Featured Image URL</label><input type="text" name="featured_image" class="form-control" value="<%= post.featured_image || \'\' %>"></div><div class="form-group"><label>Excerpt</label><textarea name="excerpt" class="form-control" rows="3"><%= post.excerpt || \'\' %></textarea></div><div class="form-group"><label style="display:flex; align-items:center; gap:0.5rem;"><input type="checkbox" name="is_featured" <%= post.is_featured ? \'checked\' : \'\' %>> Featured Post</label></div><div class="form-group"><label style="display:flex; align-items:center; gap:0.5rem;"><input type="checkbox" name="allow_comments" <%= (post.allow_comments !== false) ? \'checked\' : \'\' %>> Allow Comments</label></div><button type="submit" class="btn" style="width:100%;">Save Post</button></div></div></form>',
  'admin/categories.ejs': '<h2 style="margin-bottom:2rem;">Categories</h2><div class="grid-layout"><div class="glass glass-panel"><h3>Add New</h3><form action="/admin/categories/new" method="POST"><div class="form-group"><label>Name</label><input type="text" name="name" class="form-control" required></div><div class="form-group"><label>Description</label><textarea name="description" class="form-control"></textarea></div><button type="submit" class="btn">Save</button></form></div><div class="glass glass-panel admin-table-container"><table class="admin-table"><thead><tr><th>Name</th><th>Slug</th><th>Actions</th></tr></thead><tbody><% categories.forEach(c => { %><tr><td><%= c.name %></td><td><%= c.slug %></td><td><form action="/admin/categories/delete/<%= c.id %>" method="POST" onsubmit="return confirm(\'Delete category?\')"><button type="submit" class="btn btn-secondary" style="padding:0.2rem 0.5rem; color:var(--error);"><i class="fas fa-trash"></i></button></form></td></tr><% }) %></tbody></table></div></div>',
  'admin/tags.ejs': '<h2 style="margin-bottom:2rem;">Tags</h2><div class="grid-layout"><div class="glass glass-panel"><h3>Add New</h3><form action="/admin/tags/new" method="POST"><div class="form-group"><label>Name</label><input type="text" name="name" class="form-control" required></div><button type="submit" class="btn">Save</button></form></div><div class="glass glass-panel admin-table-container"><table class="admin-table"><thead><tr><th>Name</th><th>Slug</th><th>Actions</th></tr></thead><tbody><% tags.forEach(t => { %><tr><td><%= t.name %></td><td><%= t.slug %></td><td><form action="/admin/tags/delete/<%= t.id %>" method="POST" onsubmit="return confirm(\'Delete tag?\')"><button type="submit" class="btn btn-secondary" style="padding:0.2rem 0.5rem; color:var(--error);"><i class="fas fa-trash"></i></button></form></td></tr><% }) %></tbody></table></div></div>',
  'admin/media.ejs': '<h2 style="margin-bottom:2rem;">Media Library</h2><div class="glass glass-panel" style="margin-bottom:2rem;"><form action="/admin/media/upload" method="POST" enctype="multipart/form-data"><div style="display:flex; gap:1rem; align-items:center;"><input type="file" name="image" class="form-control" accept="image/*" required><button type="submit" class="btn">Upload</button></div></form></div><div class="media-grid"><% media.forEach(m => { %><div class="media-item"><img src="<%= m.thumbnail_url %>" alt="<%= m.filename %>"><div class="media-actions"><button class="btn btn-secondary copy-url-btn" data-url="<%= m.url %>" style="padding:0.2rem 0.5rem; font-size:0.8rem;"><i class="fas fa-link"></i></button><form action="/admin/media/delete/<%= m.id %>" method="POST" style="margin:0;" onsubmit="return confirm(\'Delete image?\')"><button type="submit" class="btn btn-secondary" style="padding:0.2rem 0.5rem; font-size:0.8rem; color:var(--error);"><i class="fas fa-trash"></i></button></form></div></div><% }) %></div>',
  'admin/comments.ejs': '<h2 style="margin-bottom:2rem;">Comments</h2><div class="glass glass-panel admin-table-container"><table class="admin-table"><thead><tr><th>Author</th><th>Comment</th><th>In Response To</th><th>Status</th><th>Actions</th></tr></thead><tbody><% comments.forEach(c => { %><tr><td><strong><%= c.name %></strong><br><small><%= c.email %></small></td><td><%= c.content %></td><td><%= c.posts ? c.posts.title : \'Unknown\' %></td><td><span class="badge badge-<%= c.status %>"><%= c.status %></span></td><td><form action="/admin/comments/update/<%= c.id %>" method="POST" style="display:inline;"><input type="hidden" name="status" value="approved"><button type="submit" class="btn btn-secondary" style="padding:0.2rem 0.5rem; color:var(--success);"><i class="fas fa-check"></i></button></form> <form action="/admin/comments/delete/<%= c.id %>" method="POST" style="display:inline;" onsubmit="return confirm(\'Delete comment?\')"><button type="submit" class="btn btn-secondary" style="padding:0.2rem 0.5rem; color:var(--error);"><i class="fas fa-trash"></i></button></form></td></tr><% }) %></tbody></table></div>',
  'admin/messages.ejs': '<h2 style="margin-bottom:2rem;">Messages</h2><div class="glass glass-panel admin-table-container"><table class="admin-table"><thead><tr><th>Name</th><th>Email</th><th>Message</th><th>Date</th></tr></thead><tbody><% messages.forEach(m => { %><tr><td><%= m.name %></td><td><a href="mailto:<%= m.email %>"><%= m.email %></a></td><td><%= m.message %></td><td><%= new Date(m.created_at).toLocaleString() %></td></tr><% }) %></tbody></table></div>',
  'admin/subscribers.ejs': '<h2 style="margin-bottom:2rem;">Subscribers</h2><div class="grid-layout"><div class="glass glass-panel"><h3>Broadcast Email</h3><form action="/admin/subscribers/broadcast" method="POST"><div class="form-group"><label>Subject</label><input type="text" name="subject" class="form-control" required></div><div class="form-group"><label>Message</label><textarea name="message" class="form-control" rows="5" required></textarea></div><button type="submit" class="btn">Send Broadcast</button></form></div><div class="glass glass-panel admin-table-container"><table class="admin-table"><thead><tr><th>Email</th><th>Status</th><th>Date</th></tr></thead><tbody><% subscribers.forEach(s => { %><tr><td><%= s.email %></td><td><span class="badge badge-<%= s.is_active ? \'published\' : \'draft\' %>"><%= s.is_active ? \'Active\' : \'Unsubscribed\' %></span></td><td><%= new Date(s.subscribed_at).toLocaleDateString() %></td></tr><% }) %></tbody></table></div></div>',
  'admin/settings.ejs': '<h2 style="margin-bottom:2rem;">Settings</h2><form action="/admin/settings" method="POST"><div class="glass glass-panel" style="max-width:800px;"><div class="form-group"><label>Blog Name (English)</label><input type="text" name="blog_name_en" class="form-control" value="<%= settings.blog_name_en || \'\' %>"></div><div class="form-group"><label>Blog Name (Malayalam)</label><input type="text" name="blog_name_ml" class="form-control" value="<%= settings.blog_name_ml || \'\' %>"></div><div class="form-group"><label>Tagline</label><input type="text" name="tagline" class="form-control" value="<%= settings.tagline || \'\' %>"></div><div class="form-group"><label>Maintenance Mode</label><select name="maintenance_mode" class="form-control"><option value="false" <%= settings.maintenance_mode === \'false\' ? \'selected\' : \'\' %>>Off</option><option value="true" <%= settings.maintenance_mode === \'true\' ? \'selected\' : \'\' %>>On</option></select></div><button type="submit" class="btn">Save Settings</button></div></form>',
  'admin/profile.ejs': '<h2 style="margin-bottom:2rem;">Profile</h2><form action="/admin/profile" method="POST"><div class="glass glass-panel" style="max-width:600px;"><div class="form-group"><label>Display Name</label><input type="text" name="display_name" class="form-control" value="<%= profile.display_name || \'\' %>" required></div><div class="form-group"><label>Bio</label><textarea name="bio" class="form-control" rows="4"><%= profile.bio || \'\' %></textarea></div><button type="submit" class="btn">Update Profile</button></div></form>',
};

if (!fs.existsSync(adminPath)) {
  fs.mkdirSync(adminPath, { recursive: true });
}

for (const [filename, content] of Object.entries(files)) {
  fs.writeFileSync(path.join(viewsPath, filename), content);
}
console.log('Views generated');
